language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage

# command to run tests
script:
   - pytest --cov=models --cov-report=xml

after_success:
  - python-codacy-coverage -r coverage.xml
